// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://anezrbrnslofrwpbfloi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuZXpyYnJuc2xvZnJ3cGJmbG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcyMTY1MzIsImV4cCI6MjA5Mjc5MjUzMn0.OFi0PRIeLQU4qUWKOI8R3ujvBwJKPyW2-XtREDSC7cA";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);